import React,{useState} from 'react';
import {ActivityIndicator,Alert,Platform,Pressable,StyleSheet,Text,TextInput,View} from 'react-native';
import {KeyboardAwareScrollViewCompat} from '@/components/KeyboardAwareScrollViewCompat';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {useAuth} from '@/context/AuthContext'; import {useColors} from '@/hooks/useColors';
export default function Auth(){const c=useColors(),insets=useSafeAreaInsets(),{login,register}=useAuth();const [join,setJoin]=useState(false),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[company,setCompany]=useState(''),[busy,setBusy]=useState(false);
 const submit=async()=>{if(!email||!password||(join&&!name)){Alert.alert('Complete your details');return}try{setBusy(true); if(join)await register({name,email,password,company});else await login(email,password)}catch(e){Alert.alert('Unable to continue',e instanceof Error?e.message:'Please try again')}finally{setBusy(false)}};
 return <KeyboardAwareScrollViewCompat style={{flex:1,backgroundColor:c.background}} contentContainerStyle={[s.wrap,{paddingTop:(Platform.OS==='web'?67:32),paddingBottom:40}]} bottomOffset={40}><Text style={[s.brand,{color:c.primary}]}>SHIPHUB</Text><Text style={[s.title,{color:c.foreground}]}>{join?'Set up your fleet':'Owner operations'}</Text><Text style={[s.sub,{color:c.mutedForeground}]}>A focused workspace for vessel owners and administrators.</Text>{join&&<Input c={c} value={name} set={setName} placeholder="Your name"/>}<Input c={c} value={email} set={setEmail} placeholder="Work email" email/>{join&&<Input c={c} value={company} set={setCompany} placeholder="Company (optional)"/>}<Input c={c} value={password} set={setPassword} placeholder="Password" password/><Pressable testID="auth-submit" onPress={submit} disabled={busy} style={[s.cta,{backgroundColor:c.primary,opacity:busy?.7:1}]}>{busy?<ActivityIndicator color={c.primaryForeground}/>:<Text style={[s.ctaText,{color:c.primaryForeground}]}>{join?'Create owner account':'Sign in'}</Text>}</Pressable><Pressable onPress={()=>setJoin(!join)}><Text style={[s.switch,{color:c.primary}]}>{join?'Already have an account? Sign in':'New owner? Create an account'}</Text></Pressable></KeyboardAwareScrollViewCompat>}
function Input({c,value,set,placeholder,password,email}:{c:ReturnType<typeof useColors>;value:string;set:(v:string)=>void;placeholder:string;password?:boolean;email?:boolean}){return <TextInput style={[s.input,{borderColor:c.border,color:c.foreground,backgroundColor:c.card}]} value={value} onChangeText={set} placeholder={placeholder} placeholderTextColor={c.mutedForeground} secureTextEntry={password} keyboardType={email?'email-address':'default'} autoCapitalize="none"/>}
const s=StyleSheet.create({wrap:{paddingHorizontal:24,gap:14,justifyContent:'center',flexGrow:1},brand:{fontFamily:'Inter_700Bold',letterSpacing:2,fontSize:14},title:{fontFamily:'Inter_700Bold',fontSize:32,marginTop:10},sub:{fontFamily:'Inter_400Regular',fontSize:15,lineHeight:22,marginBottom:18},input:{height:52,borderWidth:1,borderRadius:12,paddingHorizontal:15,fontFamily:'Inter_400Regular',fontSize:16},cta:{height:54,borderRadius:12,alignItems:'center',justifyContent:'center',marginTop:8},ctaText:{fontFamily:'Inter_700Bold',fontSize:16},switch:{textAlign:'center',fontFamily:'Inter_600SemiBold',fontSize:14,padding:10}});