import React,{useEffect,useState}from'react';
import{ActivityIndicator,Alert,Platform,Pressable,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';
import{router,useLocalSearchParams}from'expo-router';
import{useMutation,useQuery,useQueryClient}from'@tanstack/react-query';
import{useSafeAreaInsets}from'react-native-safe-area-context';
import{api}from'@/lib/api';import{useColors}from'@/hooks/useColors';import type{CharterFormData}from'@/lib/types';

export default function CharterDetail(){const c=useColors(),insets=useSafeAreaInsets(),{id}=useLocalSearchParams<{id:string}>(),charterId=Number(id),qc=useQueryClient(),q=useQuery({queryKey:['charter',charterId],queryFn:()=>api.charters.get(charterId),enabled:charterId>0});const[editing,setEditing]=useState(false),[form,setForm]=useState<CharterFormData>({});
 useEffect(()=>{if(q.data)setForm({rate:q.data.rate??'',rateCurrency:q.data.rateCurrency,rateBasis:q.data.rateBasis??'',laycanEarliest:q.data.laycanEarliest?.slice(0,10)??'',laycanLatest:q.data.laycanLatest?.slice(0,10)??'',durationDays:q.data.durationDays?String(q.data.durationDays):'',cargoPurpose:q.data.cargoPurpose??'',terms:q.data.terms??''})},[q.data]);
 const refresh=()=>{qc.invalidateQueries({queryKey:['charter',charterId]});qc.invalidateQueries({queryKey:['charters']});};
 const update=useMutation({mutationFn:()=>api.charters.update(charterId,form),onSuccess:()=>{refresh();setEditing(false)},onError:(e:Error)=>Alert.alert('Update failed',e.message)});
 const action=useMutation({mutationFn:(x:'confirm'|'decline'|'terminate')=>api.charters[x](charterId),onSuccess:refresh,onError:(e:Error)=>Alert.alert('Action failed',e.message)});
 if(q.isLoading)return <View style={[s.center,{backgroundColor:c.background}]}><ActivityIndicator color={c.primary}/></View>;const x=q.data;if(!x)return <View style={{flex:1,backgroundColor:c.background}}/>;
 const open=['enquiry','negotiating'].includes(x.status), canTerminate=x.status==='active',pad={paddingTop:(Platform.OS==='web'?67:insets.top)+12,paddingBottom:(Platform.OS==='web'?34:insets.bottom)+22};
 const confirm=(kind:'confirm'|'decline'|'terminate')=>Alert.alert(kind==='confirm'?'Confirm charter':kind==='decline'?'Decline request':'Terminate charter',kind==='terminate'?'This ends the active charter. Continue?':'Continue with this action?',[{text:'Cancel',style:'cancel'},{text:'Continue',style:kind==='confirm'?'default':'destructive',onPress:()=>action.mutate(kind)}]);
 return <ScrollView style={{flex:1,backgroundColor:c.background}} contentContainerStyle={[s.page,pad]} keyboardShouldPersistTaps="handled"><View style={s.head}><Pressable onPress={()=>router.back()}><Text style={{color:c.primary}}>Back</Text></Pressable>{open&&<Pressable onPress={()=>setEditing(!editing)}><Text style={{color:c.primary,fontFamily:'Inter_700Bold'}}>{editing?'Cancel':'Edit terms'}</Text></Pressable>}</View><Text style={[s.title,{color:c.foreground}]}>{x.vesselName??`Charter #${x.id}`}</Text><Text style={[s.status,{color:c.primary}]}>{x.status.replace('_',' ')}</Text><Card c={c} label="Charterer" value={x.chartererName??`Charterer #${x.chartererId}`}/>{editing?<Terms c={c} form={form} set={setForm}/>:<><Card c={c} label="Rate" value={x.rate?`${x.rate} ${x.rateCurrency}${x.rateBasis?` · ${x.rateBasis}`:''}`:'Not set'}/><Card c={c} label="Laycan" value={`${x.laycanEarliest?.slice(0,10)??'—'} to ${x.laycanLatest?.slice(0,10)??'—'}`}/><Card c={c} label="Duration" value={x.durationDays?`${x.durationDays} days`:'Not set'}/>{x.cargoPurpose&&<Card c={c} label="Cargo / purpose" value={x.cargoPurpose}/>} {x.terms&&<Card c={c} label="Terms" value={x.terms}/>}</>}{editing&&<Pressable onPress={()=>update.mutate()} disabled={update.isPending} style={[s.primary,{backgroundColor:c.primary}]}>{update.isPending?<ActivityIndicator color={c.primaryForeground}/>:<Text style={{color:c.primaryForeground,fontFamily:'Inter_700Bold'}}>Save negotiated terms</Text>}</Pressable>}{open&&<><Pressable onPress={()=>confirm('confirm')} style={[s.primary,{backgroundColor:c.primary}]}><Text style={{color:c.primaryForeground,fontFamily:'Inter_700Bold'}}>Confirm terms</Text></Pressable><Pressable onPress={()=>confirm('decline')} style={[s.outline,{borderColor:c.destructive}]}><Text style={{color:c.destructive,fontFamily:'Inter_600SemiBold'}}>Decline request</Text></Pressable></>}{canTerminate&&<Pressable onPress={()=>confirm('terminate')} style={[s.outline,{borderColor:c.destructive}]}><Text style={{color:c.destructive,fontFamily:'Inter_600SemiBold'}}>Terminate active charter</Text></Pressable>}</ScrollView>}
function Card({c,label,value}:{c:ReturnType<typeof useColors>;label:string;value:string}){return <View style={[s.card,{backgroundColor:c.card,borderColor:c.border}]}><Text style={{color:c.mutedForeground,fontFamily:'Inter_600SemiBold',fontSize:11,textTransform:'uppercase'}}>{label}</Text><Text style={{color:c.foreground,fontFamily:'Inter_400Regular',fontSize:15,lineHeight:21}}>{value}</Text></View>}
function Terms({c,form,set}:{c:ReturnType<typeof useColors>;form:CharterFormData;set:React.Dispatch<React.SetStateAction<CharterFormData>>}){const fields:Array<[string,keyof CharterFormData,'default'|'numeric']>=[['Rate','rate','numeric'],['Currency','rateCurrency','default'],['Rate basis','rateBasis','default'],['Laycan earliest (YYYY-MM-DD)','laycanEarliest','default'],['Laycan latest (YYYY-MM-DD)','laycanLatest','default'],['Duration days','durationDays','numeric'],['Cargo / purpose','cargoPurpose','default'],['Terms','terms','default']];return <View style={s.form}>{fields.map(([label,key,k])=><View key={key} style={{gap:5}}><Text style={{color:c.mutedForeground,fontFamily:'Inter_500Medium',fontSize:12}}>{label}</Text><TextInput value={form[key]??''} onChangeText={value=>set(x=>({...x,[key]:value}))} keyboardType={k} multiline={key==='terms'} style={[s.input,{color:c.foreground,borderColor:c.border,backgroundColor:c.card,height:key==='terms'?90:48,textAlignVertical:key==='terms'?'top':'center'}]}/></View>)}</View>}
const s=StyleSheet.create({page:{paddingHorizontal:16,gap:12},center:{flex:1,alignItems:'center',justifyContent:'center'},head:{flexDirection:'row',justifyContent:'space-between'},title:{fontFamily:'Inter_700Bold',fontSize:27},status:{fontFamily:'Inter_700Bold',fontSize:12,textTransform:'capitalize'},card:{borderWidth:1,borderRadius:12,padding:14,gap:7},form:{gap:10},input:{borderWidth:1,borderRadius:10,paddingHorizontal:12,fontFamily:'Inter_400Regular',fontSize:15},primary:{height:52,borderRadius:11,alignItems:'center',justifyContent:'center'},outline:{height:52,borderRadius:11,borderWidth:1,alignItems:'center',justifyContent:'center'}});