// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/charterer-home/Current.tsx": () => import("../components/mockups/charterer-home/Current.tsx"),
  "./components/mockups/charterer-home/NavigationMapHome.tsx": () => import("../components/mockups/charterer-home/NavigationMapHome.tsx"),
  "./components/mockups/templates/WarmFoodTestimonialCard-myiSYr/App.tsx": () => import("../components/mockups/templates/WarmFoodTestimonialCard-myiSYr/App.tsx")
};
